import type { Metadata } from 'next'
import './globals.css'
import ReduxStoreProvider from './provider/reduxStoreProvider'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        // <ReduxStoreProvider>
            <html>
                <body>{children}</body>
            </html>
        // </ReduxStoreProvider>
    )
}
