import type { Metadata } from 'next'
import './globals.css'
import ReduxStoreProvider from './provider/reduxStoreProvider'
import ReactQueryProvider from './provider/ReactQueryProvider'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html>
            <body>
                <ReduxStoreProvider>
                    <ReactQueryProvider>
                        <>{children}</>
                    </ReactQueryProvider>
                </ReduxStoreProvider>
            </body>
        </html>
    )
}
