import type { Metadata } from 'next'

import ReduxStoreProvider from './provider/reduxStoreProvider'
import ReactQueryProvider from './provider/ReactQueryProvider'
import './globals.css'
import Body from './body'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html>
            <ReduxStoreProvider>
                <ReactQueryProvider>
                    <Body>{children}</Body>
                </ReactQueryProvider>
            </ReduxStoreProvider>
        </html>
    )
}
